batch_size: 8
beta1: 0.5
birads_max: 6
birads_min: 2
conditional: false
discriminator_clf_threshold: 0.5
image_size: 128
is_condition_binary: false
is_condition_categorical: false
is_trained_on_calcifications: true
is_trained_on_masses: false
is_trained_on_other_roi_types: false
is_training_data_augmented: true
kernel_size: 6
label_smoothing_end: 1.2
label_smoothing_start: 0.7
leakiness: 0.2
lr: 0.0002
n_cond: 7
nc: 1
ndf: 64
ngf: 64
ngpu: 1
num_epochs: 500
num_iterations_between_prints: 100
nz: 100
output_model_dir: model_checkpoints/training_1619714459.3629494/
split_birads_fours: false
switch_loss_each_epoch: false
use_lsgan_loss: false
use_one_sided_label_smoothing: true
weight_decay: 5.0e-06
workers: 2
